{{- if and (.Values.Agents.SeparateNamespace.Enabled) (.Values.Agents.SeparateNamespace.Create) }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ template "agents.namespace" . }}
  labels:
    cloudbees.com/role: agents
    app.kubernetes.io/part-of: {{ .Release.Namespace }}-{{ .Release.Name }}
{{ include "cloudbees-core.labels" . | indent 4 }}
{{- end}}
