{{- if and (.Values.rbac.install) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.agentsServiceAccountName }}
  namespace: {{ template "agents.namespace" . }}
{{- if .Values.rbac.agentsServiceAccountAnnotations }}
  annotations:
{{ toYaml .Values.rbac.agentsServiceAccountAnnotations | indent 4 }}
{{- end }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
{{- if .Values.Agents.ImagePullSecrets }}
imagePullSecrets:
{{- if kindIs "string" .Values.Agents.ImagePullSecrets }}
- name: {{ .Values.Agents.ImagePullSecrets }}
{{- else }}
{{ toYaml .Values.Agents.ImagePullSecrets }}
{{- end}}
{{- end -}}
{{- end -}}
