{{- if .Values.NetworkPolicy.Enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cjoc
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
spec:
{{ include "operationsCenter.podSelector" . | indent 2 }}
  ingress:
  - from:
{{ include "master.podSelectors" . | indent 4 }}
{{ include "ingress.podSelectors" . | indent 4 }}
    ports:
    - port: {{ include "networkpolicy.cjoc.http" . }}
      protocol: TCP
    - port: {{ include "networkpolicy.cjoc.agentListener" . }}
      protocol: TCP
{{- if .Values.NetworkPolicy.JMXSelectors }}
  - from:
{{ toYaml .Values.NetworkPolicy.JMXSelectors | indent 4 }}
    ports:
      - port: {{ include "networkpolicy.cjoc.jmx" . }}
        protocol: TCP
{{- end }}
{{- end }}
