{{- if .Values.OperationsCenter.Enabled -}}
{{- if .Values.rbac.install -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
{{- if .Values.rbac.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.rbac.serviceAccountAnnotations | indent 4 }}
{{- end }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
{{- if .Values.OperationsCenter.ImagePullSecrets }}
imagePullSecrets:
{{- if kindIs "string" .Values.OperationsCenter.ImagePullSecrets }}
- name: {{ .Values.OperationsCenter.ImagePullSecrets }}
{{- else }}
{{ toYaml .Values.OperationsCenter.ImagePullSecrets }}
{{- end}}
{{- end -}}
{{- end -}}
{{- end -}}
