{{ template "validate.operationscenter" . }}
{{- if or (.Values.OperationsCenter.Enabled) (.Values.Master.OperationsCenterNamespace) -}}
{{- if .Values.Agents.SeparateNamespace.Enabled -}}
{{- if .Values.rbac.install -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cjoc-agents-test-connection
  namespace: {{ template "agents.namespace" . }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
{{- end -}}
{{- end -}}
{{- end -}}
