{{- if eq "gke" .Values.OperationsCenter.Platform -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "gke.storageclass.name" . }}
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-ssd
{{- end -}}
