{{- if .Values.Hibernation.Enabled -}}
{{- if .Values.rbac.install -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.hibernationMonitorServiceAccountName }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
{{- if .Values.Hibernation.ImagePullSecrets }}
imagePullSecrets:
{{- if kindIs "string" .Values.Hibernation.ImagePullSecrets }}
- name: {{ .Values.Hibernation.ImagePullSecrets }}
{{- else }}
{{ toYaml .Values.Hibernation.ImagePullSecrets }}
{{- end}}
{{- end -}}
{{- end -}}
{{- end -}}
