{{- if and (kindIs "bool" .Values.Hibernation.Enabled) .Values.Hibernation.Enabled -}}
{{- if include "cloudbees-core.needs-routes" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: managed-master-hibernation-monitor-namespaced
spec:
{{- if (include "hibernation.hostnamewithoutport" . ) }}
  host: {{ include "hibernation.hostnamewithoutport" . | quote }}
{{- end }}
  path: /hibernation/ns/{{ .Release.Namespace }}
  to:
    kind: Service
    name: managed-master-hibernation-monitor
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{ include "openshift.tls" . | indent 2 }}
{{ include "chart.helmRouteFix" $ }}
{{- end -}}
{{- end -}}
