{{- if .Values.Master.Enabled -}}
{{- if .Values.rbac.install -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cjoc-agents
  namespace: {{ template "agents.namespace" . }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
{{- end -}}
{{- end -}}
