{{- if .Values.Master.Enabled -}}
{{- if .Values.rbac.install -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cjoc-master-role-binding
  namespace: {{ template "agents.namespace" . }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cjoc-agents
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.masterServiceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
