{{- if and (include "psp.enabled" .) (.Values.Agents.SeparateNamespace.Enabled) }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "cb:podsecuritypolicy:restricted"
  namespace: {{ template "agents.namespace" . }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - cb.restricted-{{ .Release.Namespace }}
{{- end -}}
