annotations:
  artifacthub.io/links: |
    - name: Product overview
      url: https://www.cloudbees.com/products/continuous-integration
    - name: Documentation
      url: https://docs.cloudbees.com/docs/cloudbees-ci/latest/
apiVersion: v2
appVersion: 2.332.2.6
dependencies:
- condition: ingress-nginx.Enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.0.13
- condition: sidecarinjector.Enabled
  name: cloudbees-sidecar-injector
  repository: https://charts.cloudbees.com/public/cloudbees
  version: 2.2.1
description: Enterprise Continuous Integration with Jenkins
home: https://www.cloudbees.com/products/continuous-integration
icon: https://images.ctfassets.net/vtn4rfaw6n2j/7xprMMXARXDBuVxW4y8XfV/349fff91035050e3f2a8ff37bc0615b5/cloudbees-core-logo_header.svg
keywords:
- cloudbees
- jenkins
name: cloudbees-core
version: 3.42.6+c9672cd0453e
