{{- if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: {{ .Values.rbac.initServiceAccountName }}
  labels:
{{ include "sidecar-injector-init.labels" . | indent 4 }}
{{- end }}
