{{- if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
{{ include "sidecar-injector.labels" . | indent 4 }}
    cloudbees: sidecar-injector
{{- end}}