name: release

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  release:
    types: [published, created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v3.1

      - name: helm - add repos
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add cloudbees https://charts.cloudbees.com/public/cloudbees

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: "${{ secrets.CR_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
